patterns:
  datePatterns:
  - (?<timestamp>\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}:\d{2}\.\d+)
  - (?<timestamp>\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}:\d{2})
  - (?<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d+)
  - \[(?<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\,\d+)\]
  - (?<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\,\d+)
  - (?<timestamp>\d{2} \w{3} \d{4}\s+\d{2}:\d{2}:\d{2}\,\d+)
  dateFormatts:
  - dd/MM/yyyy HH:mm:ss.SSS
  - dd/MM/yyyy HH:mm:ss,SSS
  - dd/MM/yyyy HH:mm:ss
  - yyyy-MM-dd HH:mm:ss
  - yyyy-MM-dd HH:mm:ss,SSS
  - yyyy-MM-dd HH:mm:ss.SSS
  - dd MMM yyyy HH:mm:ss,SSS


